spring.application.name=review
server.port=8012

spring.datasource.url=JDBC:mysql://localhost:3306/review_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

eureka.client.service-url.defaultZone=http://localhost:8013/eureka/
