spring:
  application:
    name: msvc-inventory

  datasource:
    url: jdbc:h2:file:./data/inventory
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8013/eureka/
